##########################################################################
# Title:            Sandbox: Gluetun | Default Variables                 #
# Author(s):        owine                                                #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

gluetun_instances: ["gluetun"]

################################
# Settings
################################
# These variables map to the appropriate Docker ENVs
# Review the gluetun wiki (https://github.com/qdm12/gluetun/wiki)
gluetun_vpn_service_provider: "{{ omit }}"
gluetun_vpn_type: "{{ omit }}"
gluetun_openvpn_custom_config: "{{ omit }}"
gluetun_openvpn_user: "{{ omit }}"
gluetun_openvpn_password: "{{ omit }}"
gluetun_openvpn_key_passphrase: "{{ omit }}"
gluetun_vpn_endpoint_ip: "{{ omit }}"
gluetun_vpn_endpoint_port: "{{ omit }}"
gluetun_wireguard_public_key: "{{ omit }}"
gluetun_wireguard_private_key: "{{ omit }}"
gluetun_wireguard_preshared_key: "{{ omit }}"
gluetun_wireguard_addresses: "{{ omit }}"
gluetun_server_countries: "{{ omit }}"
gluetun_server_cities: "{{ omit }}"
gluetun_server_hostnames: "{{ omit }}"
gluetun_server_names: "{{ omit }}"
gluetun_server_regions: "{{ omit }}"
gluetun_firewall_vpn_input_ports: "{{ omit }}"
gluetun_firewall_input_ports: "{{ omit }}"
gluetun_firewall_outbound_subnets: "{{ omit }}"

################################
# Paths
################################

gluetun_paths_folder: "{{ gluetun_name }}"
gluetun_paths_location: "{{ server_appdata_path }}/{{ gluetun_paths_folder }}"
gluetun_paths_folders_list:
  - "{{ gluetun_paths_location }}"

################################
# Docker
################################

# Container
gluetun_docker_container: "{{ gluetun_name }}"

# Image
gluetun_docker_image_pull: true
gluetun_docker_image_repo: "qmcgaw/gluetun"
gluetun_docker_image_tag: "latest"
gluetun_docker_image: "{{ lookup('vars', gluetun_name + '_docker_image_repo', default=gluetun_docker_image_repo)
                          + ':' + lookup('vars', gluetun_name + '_docker_image_tag', default=gluetun_docker_image_tag) }}"

# Ports
gluetun_docker_ports_defaults: []
gluetun_docker_ports_custom: []
gluetun_docker_ports: "{{ lookup('vars', gluetun_name + '_docker_ports_defaults', default=gluetun_docker_ports_defaults)
                          + lookup('vars', gluetun_name + '_docker_ports_custom', default=gluetun_docker_ports_custom) }}"

# Envs
gluetun_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  VPN_SERVICE_PROVIDER: "{{ lookup('vars', gluetun_name + '_vpn_service_provider', default=(omit)) }}"
  VPN_TYPE: "{{ lookup('vars', gluetun_name + '_vpn_type', default=(omit)) }}"
  OPENVPN_CUSTOM_CONFIG: "{{ lookup('vars', gluetun_name + '_openvpn_custom_config', default=(omit)) }}"
  OPENVPN_USER: "{{ lookup('vars', gluetun_name + '_openvpn_user', default=(omit)) }}"
  OPENVPN_PASSWORD: "{{ lookup('vars', gluetun_name + '_openvpn_password', default=(omit)) }}"
  OPENVPN_KEY_PASSPHRASE: "{{ lookup('vars', gluetun_name + '_openvpn_key_passphrase', default=(omit)) }}"
  VPN_ENDPOINT_IP: "{{ lookup('vars', gluetun_name + '_vpn_endpoint_ip', default=(omit)) }}"
  VPN_ENDPOINT_PORT: "{{ lookup('vars', gluetun_name + '_vpn_endpoint_port', default=(omit)) }}"
  WIREGUARD_PUBLIC_KEY: "{{ lookup('vars', gluetun_name + '_wireguard_public_key', default=(omit)) }}"
  WIREGUARD_PRIVATE_KEY: "{{ lookup('vars', gluetun_name + '_wireguard_private_key', default=(omit)) }}"
  WIREGUARD_PRESHARED_KEY: "{{ lookup('vars', gluetun_name + '_wireguard_preshared_key', default=(omit)) }}"
  WIREGUARD_ADDRESSES: "{{ lookup('vars', gluetun_name + '_wireguard_addresses', default=(omit)) }}"
  SERVER_COUNTRIES: "{{ lookup('vars', gluetun_name + '_server_countries', default=(omit)) }}"
  SERVER_CITIES: "{{ lookup('vars', gluetun_name + '_server_cities', default=(omit)) }}"
  SERVER_HOSTNAMES: "{{ lookup('vars', gluetun_name + '_server_hostnames', default=(omit)) }}"
  SERVER_NAMES: "{{ lookup('vars', gluetun_name + '_server_names', default=(omit)) }}"
  SERVER_REGIONS: "{{ lookup('vars', gluetun_name + '_server_regions', default=(omit)) }}"
  FIREWALL_VPN_INPUT_PORTS: "{{ lookup('vars', gluetun_name + '_firewall_vpn_input_ports', default=(omit)) }}"
  FIREWALL_INPUT_PORTS: "{{ lookup('vars', gluetun_name + '_firewall_input_ports', default=(omit)) }}"
  FIREWALL_OUTBOUND_SUBNETS: "{{ lookup('vars', gluetun_name + '_firewall_outbound_subnets', default=(omit)) }}"
  HTTPPROXY: "on"
  HTTPPROXY_STEALTH: "on"
gluetun_docker_envs_custom: {}
gluetun_docker_envs: "{{ lookup('vars', gluetun_name + '_docker_envs_default', default=gluetun_docker_envs_default)
                         | combine(lookup('vars', gluetun_name + '_docker_envs_custom', default=gluetun_docker_envs_custom)) }}"

# Commands
gluetun_docker_commands_default: []
gluetun_docker_commands_custom: []
gluetun_docker_commands: "{{ lookup('vars', gluetun_name + '_docker_commands_default', default=gluetun_docker_commands_default)
                             + lookup('vars', gluetun_name + '_docker_commands_custom', default=gluetun_docker_commands_custom) }}"

# Volumes
gluetun_docker_volumes_default:
  - "{{ gluetun_paths_location }}:/gluetun"
gluetun_docker_volumes_custom: []
gluetun_docker_volumes: "{{ lookup('vars', gluetun_name + '_docker_volumes_default', default=gluetun_docker_volumes_default)
                            + lookup('vars', gluetun_name + '_docker_volumes_custom', default=gluetun_docker_volumes_custom) }}"

# Devices
gluetun_docker_devices_default: []
gluetun_docker_devices_custom: []
gluetun_docker_devices: "{{ lookup('vars', gluetun_name + '_docker_devices_default', default=gluetun_docker_devices_default)
                            + lookup('vars', gluetun_name + '_docker_devices_custom', default=gluetun_docker_devices_custom) }}"

# Hosts
gluetun_docker_hosts_default: []
gluetun_docker_hosts_custom: []
gluetun_docker_hosts: "{{ docker_hosts_common
                          | combine(lookup('vars', gluetun_name + '_docker_hosts_default', default=gluetun_docker_hosts_default))
                          | combine(lookup('vars', gluetun_name + '_docker_hosts_custom', default=gluetun_docker_hosts_custom)) }}"

# Labels
gluetun_docker_labels_default: {}
gluetun_docker_labels_custom: {}
gluetun_docker_labels: "{{ docker_labels_common
                           | combine(lookup('vars', gluetun_name + '_docker_labels_default', default=gluetun_docker_labels_default))
                           | combine(lookup('vars', gluetun_name + '_docker_labels_custom', default=gluetun_docker_labels_custom)) }}"

# Hostname
gluetun_docker_hostname: "{{ gluetun_name }}"

# Networks
gluetun_docker_networks_alias: "{{ gluetun_name }}"
gluetun_docker_networks_default: []
gluetun_docker_networks_custom: []
gluetun_docker_networks: "{{ docker_networks_common
                             + lookup('vars', gluetun_name + '_docker_networks_default', default=gluetun_docker_networks_default)
                             + lookup('vars', gluetun_name + '_docker_networks_custom', default=gluetun_docker_networks_custom) }}"

# Capabilities
gluetun_docker_capabilities_default:
  - NET_ADMIN
gluetun_docker_capabilities_custom: []
gluetun_docker_capabilities: "{{ lookup('vars', gluetun_name + '_docker_capabilities_default', default=gluetun_docker_capabilities_default)
                                 + lookup('vars', gluetun_name + '_docker_capabilities_custom', default=gluetun_docker_capabilities_custom) }}"

# Security Opts
gluetun_docker_security_opts_default: []
gluetun_docker_security_opts_custom: []
gluetun_docker_security_opts: "{{ lookup('vars', gluetun_name + '_docker_security_opts_default', default=gluetun_docker_security_opts_default)
                                  + lookup('vars', gluetun_name + '_docker_security_opts_custom', default=gluetun_docker_security_opts_custom) }}"

# Restart Policy
gluetun_docker_restart_policy: unless-stopped

# State
gluetun_docker_state: started
